import './globals.css'
import { useContext } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from '@/components/Navigation'
import DataProvider from '@/context/DataProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const mainStyle = {
  margin: '0 auto 0',
  width: '70%',
  backgroundColor: 'white',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider>
          <Navigation />
          <div style={{ height: '7vh' }}></div>
          <main style={mainStyle}>
            {children}
          </main>
        </DataProvider>
      </body>
    </html>
  )
}
